<div>
<br>
Dies ist ein Beispiel-Theme für die UB Mannheim, das bewusst einige zusätzliche Features (Menüpunkte Feedback und Layout u. a.) freigeschaltet hat und deshalb vielleicht etwas überladen wirkt.
Die Facettenvorschläge, die in VuFind standardmäßig aktiviert sind, sind allerdings hier in allen Themes deaktiviert, um die Seite etwas übersichtlicher zu machen.
Auch andere Standardfeatures (beispielsweise die sehr umfangreiche Sprachauswahl) lassen sich fast beliebig ändern oder ausschalten.
</div>
