<div>
<br>
This is an example theme for the Mannheim University Library that deliberately has some additional features enabled and therefore may appear a bit overloaded.
The facet suggestions that are activated by default in VuFind are, however, turned off in all themes here in order to make the page a little clearer.
Other standard features (for example the very extensive language selection) can also be altered almost arbitrarily or deactivated. 
</div>
