<?php $this->headTitle($this->translate('FAQs')); ?>

<h1><?=$this->transEsc('FAQs') ?></h1>

<?php if ($this->auth()->getManager()->supportsRecovery()): ?>
  <p>
    Q: Wie setze ich mein Passwort zurück?<br>
    A: Go to the login screen and click the "Forgot password" link. Enter either your user name or email address, and you will get an email containing a link to reset your password.
  </p>
<?php endif; ?>
<p>
  Q: Warum verwendet VuFind Cookies?<br>
  A: Cookies werden zur Verwaltung von Sitzungen verwendet, darunter die ausgewählte Sprache, die letzte Suche, der Inhalt des Warenkorbs, etwaige Anmeldedaten usw.
</p>
