<p>
    This is a testapplication for connecting the Discovery System <a href="https://wiki.bsz-bw.de/display/BOSS">BOSS</a> to the Integrated Library System <a href="https://wiki.bsz-bw.de/display/BWFOLIO">FOLIO</a>.
</p>
<p>
    For technical questions and suggestions: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>