<p>
    Search the Catalogue Plus of the Württemberg State Library for books, journals, articles, maps, sheet music and other media from the following holdings and collections:
    <ul>
        <li>Württemberg State Library</li>
        <li>State Bibliography Baden-Württemberg</li>
        <li>International Hölderlin Bibliography</li>
        <li>Stefan George Bibliography</li>
        <li>German Central Pharmaceutical Library</li>
        <li>Academic libraries from the GBV and SWB network regions (K10plus)</li>
        <li>freely accessible online publications (Open Access)</li>
        <li>scientific articles from numerous databases</li>
    </ul>

    If you only want to search for holdings of the Württemberg State Library, limit the Advanced Search to "WLB holdings" or use the filter "WLB holdings" in your search results. For specific searches in the State Bibliography Baden-Württemberg and the bibliographies of the literary archives of Stefan George and Friedrich Hölderlin, you can also use the corresponding restriction in the Advanced Search or the filters in your search results. Media and individual articles that are not in the WLB collection can be ordered via the "Interlibrary Loan" tab.
</p>
<br>

<p class="alert alert-danger">
    This is a beta version of the new WLB Catalogue Plus. At the moment there may still be display problems. If you find any errors, please report them by e-mail to <a href="mailto:katalogplus@wlb-stuttgart.de">katalogplus@wlb-stuttgart.de</a>. Thank you very much!
</p>


<p>
<h4>Provision times</h4>
Occasionally there may be delays in the fulfillment of your orders from our external stock. Media that can be collected are listed in your account under "Reservation". If you have entered an e-mail address, you will be informed by selecting "Notification for provided items".
</p>